import type { NextPage } from "next";
import Head from "next/head";
import Navigation from "../components/navigation";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Cas de Rooij</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <main className="text-red">Hello world</main>
    </div>
  );
};

export default Home;
