import type { NextPage } from "next";
import Head from "next/head";
import Window from "../components/Window";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cas de Rooij</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Window />
      <Window />
      <Window />
    </>
  );
};

export default Home;
